version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: build
          command: sudo ./build-docker.sh
      - store_artifacts:
          path: deploy

